# - Try to find GStreamer1 library
#
# Copyright (C) 2017 Rene Barto
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Will be defined:
#  GSTREAMER_FOUND - System has GStreamer1
#  GSTREAMER_INCLUDE_DIR - The GStreamer1 include directories
#  GSTREAMER_LIBRARIES - The libraries needed to use GStreamer1
#  GSTREAMER_DEFINITIONS - Compiler switches required for using GStreamer1

find_package(PkgConfig)
pkg_check_modules(PC_GSTREAMER gstreamer-1.0)
pkg_check_modules(PC_GSTREAMER_BASE gstreamer-base-1.0)
pkg_check_modules(PC_GSTREAMER_CHECK gstreamer-check-1.0)
pkg_check_modules(PC_GSTREAMER_CONTROLLER gstreamer-controller-1.0)
pkg_check_modules(PC_GSTREAMER_NET gstreamer-net-1.0)

if(PC_GSTREAMER_FOUND)
    set(GSTREAMER_FOUND_TEXT "Found")
else()
    set(GSTREAMER_FOUND_TEXT "Not found")
endif()

if(PC_GSTREAMER_BASE)
else()
    set(GSTREAMER_BASE_FOUND_TEXT "Not found")
endif()

if(PC_GSTREAMER_CHECK_FOUND)
    set(GSTREAMER_CHECK_FOUND_TEXT "Found")
else()
    set(GSTREAMER_CHECK_FOUND_TEXT "Not found")
endif()

if(PC_GSTREAMER_CONTROLLER_FOUND)
    set(GSTREAMER_CONTROLLER_FOUND_TEXT "Found")
else()
    set(GSTREAMER_CONTROLLER_FOUND_TEXT "Not found")
endif()

if(PC_GSTREAMER_NET_FOUND)
    set(GSTREAMER_NET_FOUND_TEXT "Found")
else()
    set(GSTREAMER_NET_FOUND_TEXT "Not found")
endif()

if(PC_GSTREAMER_FOUND)
    if(GSTREAMER_REQUIRED_VERSION)
        if (NOT "${GSTREAMER_REQUIRED_VERSION}" STREQUAL "${PC_GSTREAMER_VERSION}")
            message(WARNING "Incorrect version, please install gstreamer-1.0-${GSTREAMER_REQUIRED_VERSION}")
            set(GSTREAMER_FOUND_TEXT "Found incorrect version")
            unset(PC_GSTREAMER_FOUND)
        endif()
    endif()
endif()

if(PC_GSTREAMER_BASE_FOUND)
    if(GSTREAMER_BASE_REQUIRED_VERSION)
        if (NOT "${GSTREAMER_BASE_REQUIRED_VERSION}" STREQUAL "${PC_GSTREAMER_BASE_VERSION}")
            message(WARNING "Incorrect version, please install gstreamer-base-1.0-${GSTREAMER_BASE_REQUIRED_VERSION}")
            set(GSTREAMER_BASE_FOUND_TEXT "Found incorrect version")
            unset(PC_GSTREAMER_BASE_FOUND)
        endif()
    endif()
endif()

if(PC_GSTREAMER_CHECK_FOUND)
    if(GSTREAMER_CHECK_REQUIRED_VERSION)
        if (NOT "${GSTREAMER_CHECK_REQUIRED_VERSION}" STREQUAL "${PC_GSTREAMER_CHECK_VERSION}")
            message(WARNING "Incorrect version, please install gstreamer-check-1.0-${GSTREAMER_CHECK_REQUIRED_VERSION}")
            set(GSTREAMER_CHECK_FOUND_TEXT "Found incorrect version")
            unset(PC_GSTREAMER_CHECK_FOUND)
        endif()
    endif()
endif()

if(PC_GSTREAMER_CONTROLLER_FOUND)
    if(GSTREAMER_CONTROLLER_REQUIRED_VERSION)
        if (NOT "${GSTREAMER_CONTROLLER_REQUIRED_VERSION}" STREQUAL "${PC_GSTREAMER_CONTROLLER_VERSION}")
            message(WARNING "Incorrect version, please install gstreamer-controller-1.0-${GSTREAMER_CONTROLLER_REQUIRED_VERSION}")
            set(GSTREAMER_CONTROLLER_FOUND_TEXT "Found incorrect version")
            unset(PC_GSTREAMER_CONTROLLER_FOUND)
        endif()
    endif()
endif()

if(PC_GSTREAMER_NET_FOUND)
    if(GSTREAMER_NET_REQUIRED_VERSION)
        if (NOT "${GSTREAMER_NET_REQUIRED_VERSION}" STREQUAL "${PC_GSTREAMER_NET_VERSION}")
            message(WARNING "Incorrect version, please install gstreamer-net-1.0-${GSTREAMER_NET_REQUIRED_VERSION}")
            set(GSTREAMER_NET_FOUND_TEXT "Found incorrect version")
            unset(PC_GSTREAMER_NET_FOUND)
        endif()
    endif()
endif()

message(STATUS "libgstreamer1.0:                        ${PC_GSTREAMER_FOUND_TEXT}")
message(STATUS "PC_GSTREAMER_CFLAGS:                    ${PC_GSTREAMER_CFLAGS}")
message(STATUS "PC_GSTREAMER_CFLAGS_OTHER:              ${PC_GSTREAMER_CFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_INCLUDEDIR:                ${PC_GSTREAMER_INCLUDEDIR}")
message(STATUS "PC_GSTREAMER_INCLUDE_DIRS:              ${PC_GSTREAMER_INCLUDE_DIRS}")
message(STATUS "PC_GSTREAMER_LIBDIR:                    ${PC_GSTREAMER_LIBDIR}")
message(STATUS "PC_GSTREAMER_LIBRARY_DIRS:              ${PC_GSTREAMER_LIBRARY_DIRS}")
message(STATUS "PC_GSTREAMER_LDFLAGS:                   ${PC_GSTREAMER_LDFLAGS}")
message(STATUS "PC_GSTREAMER_LDFLAGS_OTHER:             ${PC_GSTREAMER_LDFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_LIBRARIES:                 ${PC_GSTREAMER_LIBRARIES}")

message(STATUS "libgstreamer-base1.0:                   ${PC_GSTREAMER_BASE_FOUND_TEXT}")
message(STATUS "PC_GSTREAMER_BASE_CFLAGS:               ${PC_GSTREAMER_BASE_CFLAGS}")
message(STATUS "PC_GSTREAMER_BASE_CFLAGS_OTHER:         ${PC_GSTREAMER_BASE_CFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_BASE_INCLUDEDIR:           ${PC_GSTREAMER_BASE_INCLUDEDIR}")
message(STATUS "PC_GSTREAMER_BASE_INCLUDE_DIRS:         ${PC_GSTREAMER_BASE_INCLUDE_DIRS}")
message(STATUS "PC_GSTREAMER_BASE_LIBDIR:               ${PC_GSTREAMER_BASE_LIBDIR}")
message(STATUS "PC_GSTREAMER_BASE_LIBRARY_DIRS:         ${PC_GSTREAMER_BASE_LIBRARY_DIRS}")
message(STATUS "PC_GSTREAMER_BASE_LDFLAGS:              ${PC_GSTREAMER_BASE_LDFLAGS}")
message(STATUS "PC_GSTREAMER_BASE_LDFLAGS_OTHER:        ${PC_GSTREAMER_BASE_LDFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_BASE_LIBRARIES:            ${PC_GSTREAMER_BASE_LIBRARIES}")

message(STATUS "libgstreamer-check1.0:                  ${PC_GSTREAMER_CHECK_FOUND_TEXT}")
message(STATUS "PC_GSTREAMER_CHECK_CFLAGS:              ${PC_GSTREAMER_CHECK_CFLAGS}")
message(STATUS "PC_GSTREAMER_CHECK_CFLAGS_OTHER:        ${PC_GSTREAMER_CHECK_CFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_CHECK_INCLUDEDIR:          ${PC_GSTREAMER_CHECK_INCLUDEDIR}")
message(STATUS "PC_GSTREAMER_CHECK_INCLUDE_DIRS:        ${PC_GSTREAMER_CHECK_INCLUDE_DIRS}")
message(STATUS "PC_GSTREAMER_CHECK_LIBDIR:              ${PC_GSTREAMER_CHECK_LIBDIR}")
message(STATUS "PC_GSTREAMER_CHECK_LIBRARY_DIRS:        ${PC_GSTREAMER_CHECK_LIBRARY_DIRS}")
message(STATUS "PC_GSTREAMER_CHECK_LDFLAGS:             ${PC_GSTREAMER_CHECK_LDFLAGS}")
message(STATUS "PC_GSTREAMER_CHECK_LDFLAGS_OTHER:       ${PC_GSTREAMER_CHECK_LDFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_CHECK_LIBRARIES:           ${PC_GSTREAMER_CHECK_LIBRARIES}")

message(STATUS "libgstreamer-controller1.0:             ${PC_GSTREAMER_CONTROLLER_FOUND_TEXT}")
message(STATUS "PC_GSTREAMER_CONTROLLER_CFLAGS:         ${PC_GSTREAMER_CONTROLLER_CFLAGS}")
message(STATUS "PC_GSTREAMER_CONTROLLER_CFLAGS_OTHER:   ${PC_GSTREAMER_CONTROLLER_CFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_CONTROLLER_INCLUDEDIR:     ${PC_GSTREAMER_CONTROLLER_INCLUDEDIR}")
message(STATUS "PC_GSTREAMER_CONTROLLER_INCLUDE_DIRS:   ${PC_GSTREAMER_CONTROLLER_INCLUDE_DIRS}")
message(STATUS "PC_GSTREAMER_CONTROLLER_LIBDIR:         ${PC_GSTREAMER_CONTROLLER_LIBDIR}")
message(STATUS "PC_GSTREAMER_CONTROLLER_LIBRARY_DIRS:   ${PC_GSTREAMER_CONTROLLER_LIBRARY_DIRS}")
message(STATUS "PC_GSTREAMER_CONTROLLER_LDFLAGS:        ${PC_GSTREAMER_CONTROLLER_LDFLAGS}")
message(STATUS "PC_GSTREAMER_CONTROLLER_LDFLAGS_OTHER:  ${PC_GSTREAMER_CONTROLLER_LDFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_CONTROLLER_LIBRARIES:      ${PC_GSTREAMER_CONTROLLER_LIBRARIES}")

message(STATUS "libgstreamer-net1.0:                    ${PC_GSTREAMER_NET_FOUND_TEXT}")
message(STATUS "PC_GSTREAMER_NET_CFLAGS:                ${PC_GSTREAMER_NET_CFLAGS}")
message(STATUS "PC_GSTREAMER_NET_CFLAGS_OTHER:          ${PC_GSTREAMER_NET_CFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_NET_INCLUDEDIR:            ${PC_GSTREAMER_NET_INCLUDEDIR}")
message(STATUS "PC_GSTREAMER_NET_INCLUDE_DIRS:          ${PC_GSTREAMER_NET_INCLUDE_DIRS}")
message(STATUS "PC_GSTREAMER_NET_LIBDIR:                ${PC_GSTREAMER_NET_LIBDIR}")
message(STATUS "PC_GSTREAMER_NET_LIBRARY_DIRS:          ${PC_GSTREAMER_NET_LIBRARY_DIRS}")
message(STATUS "PC_GSTREAMER_NET_LDFLAGS:               ${PC_GSTREAMER_NET_LDFLAGS}")
message(STATUS "PC_GSTREAMER_NET_LDFLAGS_OTHER:         ${PC_GSTREAMER_NET_LDFLAGS_OTHER}")
message(STATUS "PC_GSTREAMER_NET_LIBRARIES:             ${PC_GSTREAMER_NET_LIBRARIES}")

if(PC_GSTREAMER_FOUND)
    find_path(GSTREAMER_CONFIG_INCLUDE_DIR gst/gstconfig.h
        PATHS ${CMAKE_FRAMEWORK_PATH}/lib/gstreamer-1.0/include ${PC_GSTREAMER_INCLUDEDIR} ${PC_GSTREAMER_INCLUDE_DIRS})

    find_path(GSTREAMER_INCLUDE_DIR gst/gst.h
        PATHS ${CMAKE_FRAMEWORK_PATH}/include/gstreamer-1.0 ${PC_GSTREAMER_INCLUDEDIR} ${PC_GSTREAMER_INCLUDE_DIRS})

    set(GSTREAMER_LIBRARY )
    foreach(LIB ${PC_GSTREAMER_LIBRARIES})
        find_library(GSTREAMER_LIBRARY_${LIB} NAMES ${LIB}
            HINTS ${CMAKE_FRAMEWORK_PATH}/lib ${PC_GSTREAMER_LIBDIR} ${PC_GSTREAMER_LIBRARY_DIRS})
        list(APPEND GSTREAMER_LIBRARY ${GSTREAMER_LIBRARY_${LIB}})
        if (NOT GSTREAMER_LIBRARY_${LIB})
            set(GSTREAMER_FOUND_TEXT "Not found")
        endif()
    endforeach()

    if(NOT GSTREAMER_INCLUDE_DIR OR NOT GSTREAMER_LIBRARY)
        set(GSTREAMER_FOUND_TEXT "Not found")
    else()
        set(GSTREAMER_FOUND_TEXT "Found")
    endif()
endif()

if(PC_GSTREAMER_BASE_FOUND)
    find_path(GSTREAMER_BASE_INCLUDE_DIR gst/base/base.h
        HINTS ${CMAKE_FRAMEWORK_PATH}/include/gstreamer-1.0 ${PC_GSTREAMER_BASE_INCLUDEDIR} ${PC_GSTREAMER_BASE_INCLUDE_DIRS})

    set(GSTREAMER_BASE_LIBRARY )
    foreach(LIB ${PC_GSTREAMER_BASE_LIBRARIES})
        find_library(GSTREAMER_BASE_LIBRARY_${LIB} NAMES ${LIB}
            HINTS ${CMAKE_FRAMEWORK_PATH}/lib ${PC_GSTREAMER_BASE_LIBDIR} ${PC_GSTREAMER_BASE_LIBRARY_DIRS})
        list(APPEND GSTREAMER_BASE_LIBRARY ${GSTREAMER_BASE_LIBRARY_${LIB}})
        if (NOT GSTREAMER_BASE_LIBRARY_${LIB})
            set(GSTREAMER_BASE_FOUND_TEXT "Not found")
        endif()
    endforeach()

    if(NOT GSTREAMER_BASE_INCLUDE_DIR OR NOT GSTREAMER_BASE_LIBRARY)
        set(GSTREAMER_BASE_FOUND_TEXT "Not found")
    else()
        set(GSTREAMER_BASE_FOUND_TEXT "Found")
    endif()
else()
    set(GSTREAMER_BASE_FOUND_TEXT "Not found")
endif()

if(PC_GSTREAMER_CHECK_FOUND)
    find_path(GSTREAMER_CHECK_INCLUDE_DIR gst/check/check.h
        HINTS ${CMAKE_FRAMEWORK_PATH}/include/gstreamer-1.0 ${PC_GSTREAMER_CHECK_INCLUDEDIR} ${PC_GSTREAMER_CHECK_INCLUDE_DIRS})

    set(GSTREAMER_CHECK_LIBRARY )
    foreach(LIB ${PC_GSTREAMER_CHECK_LIBRARIES})
        find_library(GSTREAMER_CHECK_LIBRARY_${LIB} NAMES ${LIB}
            HINTS ${CMAKE_FRAMEWORK_PATH}/lib ${PC_GSTREAMER_CHECK_LIBDIR} ${PC_GSTREAMER_CHECK_LIBRARY_DIRS})
        list(APPEND GSTREAMER_CHECK_LIBRARY ${GSTREAMER_CHECK_LIBRARY_${LIB}})
        if (NOT GSTREAMER_CHECK_LIBRARY_${LIB})
            set(GSTREAMER_CHECK_FOUND_TEXT "Not found")
        endif()
    endforeach()

    if(NOT GSTREAMER_CHECK_INCLUDE_DIR OR NOT GSTREAMER_CHECK_LIBRARY)
        set(GSTREAMER_CHECK_FOUND_TEXT "Not found")
    else()
        set(GSTREAMER_CHECK_FOUND_TEXT "Found")
    endif()
else()
    set(GSTREAMER_CHECK_FOUND_TEXT "Not found")
endif()

if(PC_GSTREAMER_CONTROLLER_FOUND)
    find_path(GSTREAMER_CONTROLLER_INCLUDE_DIR gst/controller/controller.h
        HINTS ${CMAKE_FRAMEWORK_PATH}/include/gstreamer-1.0 ${PC_GSTREAMER_CONTROLLER_INCLUDEDIR} ${PC_GSTREAMER_CONTROLLER_INCLUDE_DIRS})

    set(GSTREAMER_CONTROLLER_LIBRARY )
    foreach(LIB ${PC_GSTREAMER_CONTROLLER_LIBRARIES})
        find_library(GSTREAMER_CONTROLLER_LIBRARY_${LIB} NAMES ${LIB}
            HINTS ${CMAKE_FRAMEWORK_PATH}/lib ${PC_GSTREAMER_CONTROLLER_LIBDIR} ${PC_GSTREAMER_CONTROLLER_LIBRARY_DIRS})
        list(APPEND GSTREAMER_CONTROLLER_LIBRARY ${GSTREAMER_CONTROLLER_LIBRARY_${LIB}})
        if (NOT GSTREAMER_CONTROLLER_LIBRARY_${LIB})
            set(GSTREAMER_CONTROLLER_FOUND_TEXT "Not found")
        endif()
    endforeach()

    if(NOT GSTREAMER_CONTROLLER_INCLUDE_DIR OR NOT GSTREAMER_CONTROLLER_LIBRARY)
        set(GSTREAMER_CONTROLLER_FOUND_TEXT "Not found")
    else()
        set(GSTREAMER_CONTROLLER_FOUND_TEXT "Found")
    endif()
else()
    set(GSTREAMER_CONTROLLER_FOUND_TEXT "Not found")
endif()

if(PC_GSTREAMER_NET_FOUND)
    find_path(GSTREAMER_NET_INCLUDE_DIR gst/net/gstnet.h
        HINTS ${CMAKE_FRAMEWORK_PATH}/include/gstreamer-1.0 ${PC_GSTREAMER_NET_INCLUDEDIR} ${PC_GSTREAMER_NET_INCLUDE_DIRS})

    set(GSTREAMER_NET_LIBRARY )
    foreach(LIB ${PC_GSTREAMER_NET_LIBRARIES})
        find_library(GSTREAMER_NET_LIBRARY_${LIB} NAMES ${LIB}
            HINTS ${CMAKE_FRAMEWORK_PATH}/lib ${PC_GSTREAMER_NET_LIBDIR} ${PC_GSTREAMER_NET_LIBRARY_DIRS})
        list(APPEND GSTREAMER_NET_LIBRARY ${GSTREAMER_NET_LIBRARY_${LIB}})
        if (NOT GSTREAMER_NET_LIBRARY_${LIB})
            set(GSTREAMER_NET_FOUND_TEXT "Not found")
        endif()
    endforeach()

    if(NOT GSTREAMER_NET_INCLUDE_DIR OR NOT GSTREAMER_NET_LIBRARY)
        set(GSTREAMER_NET_FOUND_TEXT "Not found")
    else()
        set(GSTREAMER_NET_FOUND_TEXT "Found")
    endif()
else()
    set(GSTREAMER_NET_FOUND_TEXT "Not found")
endif()

message(STATUS "libgstreamer1.0-config:       ")
message(STATUS "  include dirs:               ${GSTREAMER_CONFIG_INCLUDE_DIR}")

message(STATUS "libgstreamer1.0:              ${GSTREAMER_FOUND_TEXT}")
message(STATUS "  include dirs:               ${GSTREAMER_INCLUDE_DIR}")
message(STATUS "  libs:                       ${GSTREAMER_LIBRARY}")

message(STATUS "libgstreamer-base1.0:         ${GSTREAMER_BASE_FOUND_TEXT}")
message(STATUS "  include dirs:               ${GSTREAMER_BASE_INCLUDE_DIR}")
message(STATUS "  libs:                       ${GSTREAMER_BASE_LIBRARY}")

message(STATUS "libgstreamer-check1.0:        ${GSTREAMER_CHECK_FOUND_TEXT}")
message(STATUS "  include dirs:               ${GSTREAMER_CHECK_INCLUDE_DIR}")
message(STATUS "  libs:                       ${GSTREAMER_CHECK_LIBRARY}")

message(STATUS "libgstreamer-controller1.0:   ${GSTREAMER_CONTROLLER_FOUND_TEXT}")
message(STATUS "  include dirs:               ${GSTREAMER_CONTROLLER_INCLUDE_DIR}")
message(STATUS "  libs:                       ${GSTREAMER_CONTROLLER_LIBRARY}")

message(STATUS "libgstreamer-net1.0:          ${GSTREAMER_NET_FOUND_TEXT}")
message(STATUS "  include dirs :              ${GSTREAMER_NET_INCLUDE_DIR}")
message(STATUS "  libs:                       ${GSTREAMER_NET_LIBRARY}")

set(GSTREAMER_DEFINITIONS ${PC_GSTREAMER_CFLAGS_OTHER})

set(GSTREAMER_BASE_DEFINITIONS ${PC_GSTREAMER_BASE_CFLAGS_OTHER})

set(GSTREAMER_CHECK_DEFINITIONS ${PC_GSTREAMER_CHECK_CFLAGS_OTHER})

set(GSTREAMER_CONTROLLER_DEFINITIONS ${PC_GSTREAMER_CONTROLLER_CFLAGS_OTHER})

set(GSTREAMER_NET_DEFINITIONS ${PC_GSTREAMER_NETCFLAGS_OTHER})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GSTREAMER DEFAULT_MSG
    GSTREAMER_LIBRARY GSTREAMER_INCLUDE_DIR)
find_package_handle_standard_args(GSTREAMER_BASE DEFAULT_MSG
    GSTREAMER_BASE_LIBRARY GSTREAMER_BASE_INCLUDE_DIR)
find_package_handle_standard_args(GSTREAMER_CHECK DEFAULT_MSG
    GSTREAMER_CHECK_LIBRARY GSTREAMER_CHECK_INCLUDE_DIR)
find_package_handle_standard_args(GSTREAMER_CONTROLLER DEFAULT_MSG
    GSTREAMER_CONTROLLER_LIBRARY GSTREAMER_CONTROLLER_INCLUDE_DIR)
find_package_handle_standard_args(GSTREAMER_NET DEFAULT_MSG
    GSTREAMER_NET_LIBRARY GSTREAMER_NET_INCLUDE_DIR)

mark_as_advanced(
    GSTREAMER_CONFIG_INCLUDE_DIR
    GSTREAMER_INCLUDE_DIR GSTREAMER_LIBRARY
    GSTREAMER_BASE_INCLUDE_DIR GSTREAMER_BASE_LIBRARY
    GSTREAMER_CHECK_INCLUDE_DIR GSTREAMER_CHECK_LIBRARY
    GSTREAMER_CONTROLLER_INCLUDE_DIR GSTREAMER_CONTROLLER_LIBRARY
    GSTREAMER_NET_INCLUDE_DIR GSTREAMER_NET_LIBRARY)
