# - Try to Find libxkbcommon
# Once done, this will define
#
#  LIB_XKB_COMMON_FOUND - system has EGL installed.
#  LIB_XKB_COMMON_INCLUDE_DIRS - directories which contain the EGL headers.
#  LIB_XKB_COMMON_LIBRARIES - libraries required to link against EGL.
#  LIB_XKB_COMMON_DEFINITIONS - Compiler switches required for using EGL.
#


find_package(PkgConfig)

pkg_check_modules(PC_LIB_XKB_COMMON xkbcommon)

if (PC_LIB_XKB_COMMON_FOUND)
    message(STATUS "Found xkbcommon.pc")
    message(STATUS "PC_LIB_XKB_COMMON_CFLAGS:           ${PC_LIB_XKB_COMMON_CFLAGS}")
    message(STATUS "PC_LIB_XKB_COMMON_CFLAGS_OTHER:     ${PC_LIB_XKB_COMMON_CFLAGS_OTHER}")
    message(STATUS "PC_LIB_XKB_COMMON_INCLUDEDIR:       ${PC_LIB_XKB_COMMON_INCLUDEDIR}")
    message(STATUS "PC_LIB_XKB_COMMON_INCLUDE_DIRS:     ${PC_LIB_XKB_COMMON_INCLUDE_DIRS}")
    message(STATUS "PC_LIB_XKB_COMMON_LIBDIR:           ${PC_LIB_XKB_COMMON_LIBDIR}")
    message(STATUS "PC_LIB_XKB_COMMON_LIBRARY_DIRS:     ${PC_LIB_XKB_COMMON_LIBRARY_DIRS}")
    message(STATUS "PC_LIB_XKB_COMMON_LDFLAGS:          ${PC_LIB_XKB_COMMON_LDFLAGS}")
    message(STATUS "PC_LIB_XKB_COMMON_LDFLAGS_OTHER:    ${PC_LIB_XKB_COMMON_LDFLAGS_OTHER}")
    message(STATUS "PC_LIB_XKB_COMMON_LIBRARIES:        ${PC_LIB_XKB_COMMON_LIBRARIES}")

    set(LIB_XKB_COMMON_DEFINITIONS ${PC_LIB_XKB_COMMON_CFLAGS_OTHER})
endif ()

find_path(LIB_XKB_COMMON_INCLUDE_DIRECTORY NAMES xkbcommon/xkbcommon.h
        HINTS ${CMAKE_FRAMEWORK_PATH}/include ${PC_LIB_XKB_COMMON_INCLUDEDIR} ${PC_LIB_XKB_COMMON_INCLUDE_DIRS}
        )

set(LIB_XKB_COMMON_NAMES ${PC_LIB_XKB_COMMON_LIBRARIES})
find_library(LIB_XKB_COMMON_LIBRARIES NAMES ${LIB_XKB_COMMON_NAMES}
        HINTS ${CMAKE_FRAMEWORK_PATH}/lib ${PC_LIB_XKB_COMMON_LIBDIR} ${PC_LIB_XKB_COMMON_LIBRARY_DIRS}
        )
message(STATUS "LIB_XKB_COMMON_INCLUDE_DIRECTORY:   ${LIB_XKB_COMMON_INCLUDE_DIRECTORY}")
message(STATUS "LIB_XKB_COMMON_LIBRARIES:           ${LIB_XKB_COMMON_LIBRARIES}")

if (NOT ${LIB_XKB_COMMON_INCLUDE_DIRECTORY} STREQUAL "" AND
    NOT ${LIB_XKB_COMMON_LIBRARIES} STREQUAL "")
    message(STATUS "Found libxkbcommon")
else()
    message(SEND_ERROR "Could not find libxkbcommon. Please install: sudo apt-get install libxkbcommon-dev")
endif()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIB_XKB_COMMON DEFAULT_MSG LIB_XKB_COMMON_INCLUDE_DIRECTORY LIB_XKB_COMMON_LIBRARIES)

mark_as_advanced(LIB_XKB_COMMON_INCLUDE_DIRECTORY LIB_XKB_COMMON_LIBRARIES)